"""partial_unique_index

Revision ID: 5b4699b3b1c9
Revises: 1a0157395e02
Create Date: 2026-10-02 10:17:05.090852

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b4699b3b1c9"
down_revision: str | Sequence[str] | None = "1a0157395e02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_cars_number_parked",
        "cars",
        ["number"],
        unique=True,
        postgresql_where=sa.text("status = 'parked'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_cars_number_parked",
        table_name="cars",
        postgresql_where=sa.text("status = 'parked'"),
    )
    # ### end Alembic commands ###
