services:

  parking:
    build: .
    container_name: parking_app
    env_file: .env.prod
    ports:
      - "8000:8000"
    networks:
      - parking_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"

  postgres:
      image: postgres:17
      container_name: parking_db
      env_file: 
        .env.prod
      ports:
        - "5432:5432"  
      volumes:
        - parking_data:/var/lib/postgresql/data
      networks:
        - parking_network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - parking_network


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    networks:
      - parking_network


volumes:
  parking_data:

networks:
  parking_network:
    driver: bridge 
