from contextlib import AbstractContextManager
from contextlib import nullcontext as does_not_raise
from datetime import datetime
from uuid import UUID, uuid4

from pydantic import ValidationError
from pytest import mark, param, raises

from app.domains.v1.cars.schemas import CarUnparkSchema, CursorPaginationSchema, ParkingReadSchema
from app.models.car import CarStatus


@mark.parametrize(
    "id, mark, model, number, color, status, created_at, updated_at, exc",
    [
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="correct_id",
        ),
        param(
            1,
            "Toyota",
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            raises(ValidationError),
            id="incorrect_id",
        ),
        param(
            uuid4(),
            "AU",
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="min_length_mark",
        ),
        param(
            uuid4(),
            "AUT",
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="min_length_mark+1",
        ),
        param(
            uuid4(),
            "A",
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            raises(ValidationError),
            id="too_short_mark",
        ),
        param(
            uuid4(),
            "AU" * 25,
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="max_length_mark",
        ),
        param(
            uuid4(),
            "AUTOMOB" * 7,
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="max_length_mark-1",
        ),
        param(
            uuid4(),
            "AUT" * 17,
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            raises(ValidationError),
            id="too_long_mark_length",
        ),
        param(
            uuid4(),
            "Toyota",
            "Co",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="min_length_model",
        ),
        param(
            uuid4(),
            "Toyota",
            "Cor",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="min_length_model+1",
        ),
        param(
            uuid4(),
            "Toyota",
            "C",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            raises(ValidationError),
            id="too_short_model",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corol" * 10,
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="max_length_model",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla" * 7,
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="max_length_model-1",
        ),
        param(
            uuid4(),
            "Toyota",
            "Cor" * 17,
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            raises(ValidationError),
            id="too_long_model_length",
        ),
        # ------------------------------------------------
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="min_length_number",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756рd",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="min_length_number+1",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            raises(ValidationError),
            id="too_short_model",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756рxx",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="max_length_model",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756рx",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="max_length_model-1",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756рxxx",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            raises(ValidationError),
            id="too_long_model_length",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756р",
            "red",
            CarStatus.parked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="status_parked",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756р",
            "red",
            CarStatus.unparked,
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="status_unparked",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756р",
            "red",
            "incorect_status",
            datetime.now(),
            datetime.now(),
            raises(ValidationError),
            id="incorrect_status_value",
        ),
        param(
            uuid4(),
            "Toyota",
            "Corolla",
            "ал756р",
            "red",
            "parked",
            datetime.now(),
            datetime.now(),
            does_not_raise(),
            id="correct_status_type",
        ),
    ],
)
def test_get_park_price_schema(
    id: UUID,
    mark: str,
    model: str,
    number: str,
    color: str,
    status: CarStatus,
    created_at: datetime,
    updated_at: datetime,
    exc: AbstractContextManager[object],
):
    with exc:
        ParkingReadSchema(
            id=id,
            mark=mark,
            model=model,
            number=number,
            color=color,
            status=status,
            created_at=created_at,
            updated_at=updated_at,
        )


@mark.parametrize(
    "number, exc",
    [
        param("ал756р", does_not_raise(), id="corect_unpark_data"),
        param("ал756р", does_not_raise(), id="min_length_number"),
        param("ал756", raises(ValidationError), id="too_short_length_number"),
        param("ал756рxx", does_not_raise(), id="max_length_number"),
        param("ал756рx", does_not_raise(), id="max_length_number-1"),
        param("ал756рxxx", raises(ValidationError), id="too_long_length_number"),
    ],
)
async def test_unpark_car_schema(number: str, exc: AbstractContextManager[object]):
    with exc:
        CarUnparkSchema(number=number)


@mark.parametrize(
    "limit, cursor_id, created_at, exc",
    [
        param(5, None, None, does_not_raise(), id="correct_limit_and_cursor_id_and_created_at"),
        param(5, uuid4(), datetime.now(), does_not_raise(), id="correct_request"),
        param(1, uuid4(), datetime.now(), does_not_raise(), id="limit_at_min"),
        param(50, uuid4(), datetime.now(), does_not_raise(), id="limit_at_max"),
        param(0, uuid4(), datetime.now(), raises(ValidationError), id="limit_less_than_min"),
        param(51, uuid4(), datetime.now(), raises(ValidationError), id="limit_more_than_max"),
        param(
            5,
            uuid4(),
            None,
            raises(ValidationError),
            id="created_at_is_none_while_cursor_id_is_not_none",
        ),
        param(
            5,
            None,
            datetime.now(),
            raises(ValidationError),
            id="cursor_id_is_none_while_created_at_is_not_none",
        ),
    ],
)
async def test_cursor_pagination(
    limit: int,
    cursor_id: UUID | None,
    created_at: datetime | None,
    exc: AbstractContextManager[object],
):
    with exc:
        CursorPaginationSchema(limit=limit, cursor_id=cursor_id, created_at=created_at)
